### ISSUE TITLE
Show time left counter on popup

### ISSUE THREAD

**Issue by udine1981** [juanperi/jquerySessionTimeoutHandler#7]
Hi,

Great plugin and really good job. It works like a charm. I have juste one problem.
I would like to show to my customers the time left before logout on the dialog box. Dynamic counter of course.
How can I do that ? I had try some tricks without any success.

Thx for answer.

**Comment by juanperi** [comment]
You can't do that with the current architecture, as everything is handled by settimeouts. If you really want to do that, a rearchitecture of the plugin will be needed.

Sorry about that!

**Comment by udine1981** [comment]
Ok, thanks a lot for your answer. Have a nice day.
